export const PRODUCT_CONSTRAINTS = {
  NAME_MIN: 3,
  NAME_MAX: 60,
  DESCRIPTION_MAX: 500,
  DESCRIPTION_MIN: 10,
  VALUE_MIN: 0,
  VALUE_MAX: 1000,
  PHOTO_URL_MIN: 10,
  PHOTO_URL_MAX: 2048,
} as const;
